config/routes.rb
Rails.application.routes.draw do
  resources :articles
  root 'pages#home'
  get 'about', to:'pages#about'
  get 'signup', to:'users#new'  
  resources :users, except: [:new]
  resources :categories
  # , except: [:destroy]

  get 'login', to:'sessions#new'  
  post 'login', to:'sessions#create'  
  delete 'logout', to:'sessions#destroy'  
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: {minimum:4, maximum:20}
    validates :description, presence: true, length: {minimum:14, maximum:200}
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  # before_action :require_user, except: [:show, :index]
#  before_action :require_same_user, only: [:edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  def show
    if @article
      render json: @article
    else
      render json: { message: "not present" }, status: 201
    end
  end

  def index
    # @articles = Article.paginate(page: params[:page], per_page: 5)
    @articles = Article.all
    render json: @articles, status: 200
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
  #   @article.title=params[:title]
  #   @article.description=params[:description]
  #  # @article.category_ids[]=params[:category_ids=>[]]
    @article.user = User.last
    # render json:@article,status: :created
    debugger
    if @article.save
      # flash[:notice] = "created successfully"
      render json: @article, status: :created
      #redirect_to (@article)
    else
      #   # render "new"
      #   # redirect_to (@article)
      render json: { message: "not created" }, status: 201
    end
  end

  def update
    if @article.update(article_params)
    # @article.title=params[:title]
    # @article.description=params[:description]
    #   #flash[:notice] = "updated successfully"
      # redirect_to (@article)
      render json: { message: "updated" }, status: 200
    else
      # render "edit"
      render json: { message: "not updated" }, status: 200
    end
  end

  def destroy
    if @article.destroy
      render json: {message:"deleted"}
    else
      render json: { message: "not deleted" }
      #   # redirect_to articles_path, status: :see_other
    end
  end

  private

  def set_article
    if ((Article.find_by_id(params[:id])))
      @article = Article.find(params[:id])
    else
      render json: { message: "not present" }, status: 200
    end
  end

  def article_params
    params.permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if ((current_user != @article.user) && !current_user.admin?)
      # flash[:alert] = "only #{@article.user.username} can edit or delete this article"
        render json:{message:"You cannot delete this article"}
      # redirect_to @article
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div class="container ">
<% obj.each do |article| %>
<div class="row justify-content-md-center">
<div class="col-8 mt-3 ">

<div class="card text-center shadow mb-3 bg-white rounded">
  <div class="card-header font-italic">
    <% if article.user %>
    by <%= link_to article.user.username, user_path(article.user) %>
    <% end %>
    <div class="mt-2">
     <%if article.categories.any?%>
    <%= render article.categories%>
    <%end%>
    </div>
 
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
    <p class="card-text"><%= truncate(article.description, length: 20) %></p>
    <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
    <% if loggedin? && (current_user == article.user || current_user.admin?) %>
    <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-warning" %>
    <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger",
                                           data: { turbo_confirm: "Are You Sure ?",
                                            turbo_method: :delete } %>
    <% end %>

  </div>
  <div class="card-footer text-muted">
 <small>Created <%= time_ago_in_words(article.created_at) %> ago, 
 edited <%= time_ago_in_words(article.updated_at) %> ago</small>
  </div>

</div>

</div>

<div class="row mb-5 text-center">
      
<%= link_to "[Create a New Article]", new_article_path, class: "text-success " %>

</div>

</div>
<% end %>
   </div>

app/views/articles/_form.html.erb
<div class="container">
  <%= render 'shared/errors',obj:@article%>
   <div class="row justify-content-center">
     <div class="col-10">
      <%= form_with(model: @article ,class:"shadow mb-5 p-3 bg-info rounded", local: true, data: { turbo: false })  do |f| %>

         <div class="form-group row">
             <%= f.label :title , class:"col-2 col-form-label text-light"%><br/>
             <div class="col-10">
               <%= f.text_field :title, class:"form-control shadow rounded",placeholder:"Title of article"%>
            </div>
         </div>

         <div class="form-group row mt-2">
            <%= f.label :description , class:"col-2  col-form-label text-light"%><br/>
            <div class="col-10">
               <%= f.text_area :description,rows:10 , class:"form-control shadow rounded", placeholder:"Description of article" %>
            </div>
         </div>

         <div class="form-group row mt-2">
            <%= f.label :Categories , class:"col-2  col-form-label text-light"%><br/>
            <div class="col-10">
            <%= f.collection_select(:category_ids, Category.all, :id, :name,
            {prompt:"make your selection (can be empty)"},{multiple:true,size:3,class:"form-select shadow rounded"})%>
            </div>
         </div>


         <div class="form-group row mt-4 justify-content-center">
         <div class="col-2">
           <%= f.submit class:"btn btn-outline-light btn-lg" %>
           </div>
         </div>
     <% end %>
   </div>
      <div class="row text-center ">
    <%= link_to '[Back to List of Articles]',articles_path , class:"text-success"%>

         </div>
</div>
 </div>

app/views/articles/edit.html.erb
<h1 class="text-center">Edit article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">List Of Articles</h1>

<div class="flickr_pagination">
<%= will_paginate @articles, :container => false %>
  </div>
<%= render 'article',obj:@articles%>

<div class="flickr_pagination">
<%= will_paginate @articles, :container => false %>
  </div>

app/views/articles/new.html.erb
<h1 class="text-center">Create a new article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h1 class="text-center mt-4"><%= @article.title %></h1>
<div class="container ">
<div class="row justify-content-md-center">
<div class="col-8 mt-3 ">

<div class="card text-center shadow mb-5 bg-white rounded">
  <div class="card-header font-italic">
    by <%= @article.user.username %>
    <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
    <%if @article.categories.any?%>
    <%= render @article.categories%>
    <%end%>
  </div>
  <div class="card-body">
    <div class="card-text"><%= simple_format(@article.description) %></div>
    <% if loggedin? && (current_user == @article.user || current_user.admin?) %>
    <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-warning" %>
    <%= link_to "Delete", article_path(@article), class: "btn btn-outline-danger",
                                            data: { turbo_confirm: "Are You Sure ?", turbo_method: :delete } %>
<% end %>
  </div>
  <div class="card-footer text-muted">
 <small>Created <%= time_ago_in_words(@article.created_at) %> ago, 
 edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
  </div>

</div>

</div>

<div class="row  mt-2 mb-2 text-center">
      
<%= link_to "[Create a New Article]", new_article_path, class: "text-success " %>

</div>

</div>

   </div>