config/routes.rb
Rails.application.routes.draw do
  resources :articles
  root 'pages#home'
  get 'about', to:'pages#about'
  get 'signup', to:'users#new'  
  resources :users, except: [:new]
  resources :categories
  # , except: [:destroy]

  get 'login', to:'sessions#new'  
  post 'login', to:'sessions#create'  
  delete 'logout', to:'sessions#destroy'  
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true,
                   uniqueness: { case_sensitive: false },
                   length: { minimum: 4, maximum: 20 }

  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update,:destroy]
  # before_action :require_user, except: [:show, :index]
  # before_action :require_admin, except: [:index, :show,:edit]
   skip_before_action :verify_authenticity_token

  def new
    @category = Category.new
  end

  def edit
  end

  def destroy
    if @category.destroy
      render json: { message: "category destroyed" }
    else
      render json: { message: "category not destroyed" }
    end
  end

  def update
      if @category.update(category_params)
      render json: { message: "Category Updated" }

      #   flash[:notice] = "updated successfully"
      #   redirect_to category_path(@category)
    else
      #   render "edit"
      render json: { message: "not updated" }
    end
  end

  def index
    # @categories = Category.paginate(page: params[:page], per_page: 5)
    @categories = Category.all
    render json: @categories
  end

  def show
    # @articles = @category.articles.paginate(page: params[:page], per_page:5)
    render json: @category
  end

  def create
    @category = Category.new(category_params)
    debugger
    if @category.save
      # flash[:notice] = "created successfully"
      # redirect_to @category
      debugger
      render json: { message: " created " }
    else
      debugger
      render json: { message: " could not create" }
      # render "new"
    end
  end

  private

  def category_params

    params.permit(:name)
  end

  def set_category
    if ((Category.find_by_id(params[:id])))
      @category = Category.find(params[:id])
    else
      render json: { message: "not present" }, status: 200
    end
  end

  def require_admin
    if !(loggedin? && current_user.admin?)
      render json: { message: "only admin can perform this action" }, status: 200
      # flash[:alert] = "Only Admin can perform this action"
      # redirect_to categories_path
    end
  end
end

app/views/categories/_category.html.erb
         <h5 class="badge badge-pill bg-info"><%=link_to category.name,category_path(category)%></h5>

app/views/categories/_form.html.erb
<div class="container">
  <%= render 'shared/errors', obj:@category%>
   <div class="row justify-content-center">
     <div class="col-10">
      <%= form_with(model:@category ,class:"shadow mt-5 p-3 bg-info rounded", local: true, data: { turbo: false })  do |f| %>

         <div class="form-group row">
             <%= f.label :name,"Category name" , class:"col-2 col-form-label text-light"%><br/>
             <div class="col-10">
               <%= f.text_field :name, class:"form-control shadow rounded",placeholder:"Enter name"%>
            </div>
         </div>
         <div class="form-group row mt-4 justify-content-center">
         <div class="col-2">
           <%= f.submit ( @category.new_record? ? "Add Category":"Update Category"), class:"btn btn-outline-light btn-lg"%>
           </div>
         </div>
     <% end %>
   </div>
</div>
 </div>

app/views/categories/edit.html.erb
<h1 class="text-center">Edit Category</h1>
<%= render 'form' %>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">List Of categories</h1>

<div class="flickr_pagination">
<%= will_paginate @categories, :container => false %>
  </div>

<div class="container ">
<% @categories.each do |category| %>
<div class="row justify-content-md-center">
  <div class="col-6 mt-3 ">

    <div class="card text-center shadow mb-3 bg-white rounded">
        <div class="card-header font-italic">
         <h5 class="card-title "><%= link_to category.name, category_path(category), class: "text-success " %></h5>
         </div>
        <div class="card-body">
          <p class="card-text mt-1"><%= pluralize(category.articles.count, "article") %></p>
        </div>
    <div class="card-footer text-muted">
 <small>Created <%= time_ago_in_words(category.created_at) %> ago, 
 edited <%= time_ago_in_words(category.updated_at) %> ago</small>
  </div>

    </div>

  </div>

</div>
<% end %>
   </div>

<div class="flickr_pagination">
<%= will_paginate @categories, :container => false %>
  </div>

app/views/categories/new.html.erb
<h1 class="text-center">Create a new Category</h1>
<%= render 'form' %>

app/views/categories/show.html.erb
<h3 class="text-center mt-4"><%=@category.name%>'s Articles are </h3>

<div class="text-center mt-4 ">
 <% if (loggedin? && current_user.admin?)%>
 <%=link_to "Edit Category ",edit_category_path(@category),class:"btn btn-outline-success " %>
 </div>
 <%end%>  
<div class="flickr_pagination">
 <%= will_paginate @articles, :container => false %> 
  </div> 
<%= render 'articles/article',obj:@category.articles%>