config/routes.rb
Rails.application.routes.draw do
  resources :articles
  root 'pages#home'
  get 'about', to:'pages#about'
  get 'signup', to:'users#new'  
  resources :users, except: [:new]
  resources :categories
  # , except: [:destroy]

  get 'login', to:'sessions#new'  
  post 'login', to:'sessions#create'  
  delete 'logout', to:'sessions#destroy'  
end

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto py-3 bg-dark">
  <div class="container">
    <span class="text-muted">copyright@ ab</span>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
<div class="container">
   <div class="row justify-content-center">
     <div class="col">
    <% if flash.notice %>
<div class="alert alert-success rounded alert-dismissible fade show" role="alert">
<% else %>
<div class="alert alert-danger rounded alert-dismissible fade show" role="alert">
<% end %>
    <%= msg %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        </div>
        </div>
        </div>
    
   <% end %>

app/views/layouts/_navigation.html.erb
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
  <% if !loggedin? %>
    <%= link_to "ALPHA-BLOG ", root_path, class: "navbar-title me-3" %>
    <% else %>
     <%= link_to "ALPHA-BLOG ", articles_path, class: "navbar-title me-3" %>
     <% end %>
   
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Users", users_url, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          <li><%= link_to "List of Articles", articles_path, class: "dropdown-item" %></li>
              <% if loggedin? %>
            <li><%= link_to "Create new Article", new_article_path, class: "dropdown-item" %></li>
            <% end %>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          <li><%= link_to "List of Categories", categories_path, class: "dropdown-item" %></li>
              <% if (loggedin? && current_user.admin? )%>
            <li><%= link_to "Create new Category", new_category_path, class: "dropdown-item" %></li>
            <% end %>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>




        <% if !loggedin? %>
        <li class="nav-item">
          <li><%= link_to "Log in", login_path, class: "nav-link" %></li>   
        </li>
        <li class="nav-item">
          <li><%= link_to "Sign up", signup_path, class: "nav-link" %></li>   
        </li>
        <% else %> 
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= "(admin)" if current_user.admin? %> <%=current_user.username %>
            
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          <li><%= link_to "View Profile", user_path(current_user), class: "dropdown-item" %></li>
            <li><%= link_to "Edit Profile", edit_user_path(current_user), class: "dropdown-item" %></li> 
            <li><%= link_to "Delete Profile", user_path(current_user),
                            class: "dropdown-item text-danger",
                            data: { turbo_confirm: "Are You Sure ?",
                                    turbo_method: :delete } %></li>   
        
                   </ul>
        </li>
        <li class="nav-item">
          <li><%= link_to "Log out", logout_path, class: "nav-link",
                                                  data: { turbo_confirm: "Are You Sure ?",
                                                          turbo_method: :delete } %></li>   
        </li>
        <% end %>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alpha-blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "layouts/navigation" %>  
  <%= render "layouts/messages" %>  
  <%= yield %>
  <%= render "layouts/footer" %>
  </body>
</html>